# Generated by Django 5.2.7 on 2025-12-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_category_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
