# Generated by Django 5.2.7 on 2026-01-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_paid_at_order_paystack_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='address not provided', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='city not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='state not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('best_seller', 'Best Seller'), ('top_rated', 'Top Rated'), ('special_sale', 'Special Sale')], default='new_arrival', max_length=20),
        ),
    ]
